name: GUIShop
main: com.pablo67340.shop.main.Main
version: 6.3
author: pablo67340
description: Plugin for any server.
softdepend: [SilkSpawners, Vault]
permissions:
    guishop.use:
        default: false
        description: Grants access to GUIShop
    guishop.slot.*:
        default: false
        description: Grants access to specific items in shop
    guishop.reload:
        default: false
        description: Grants access to reload shops
    guishop.creator:
        default: false
        description: Grants access to GUIShop Creator